### PR TITLE
Huge Update: Refactoring and Optimizations

### PR DESCRIPTION
**Pull request by illiafox**
1. Refactor
2. Added RW mutex for faster resources mutexes access
3. Wrapped errors
4. Removed stat()
5. Optimized code

6. Contribution table in readme
TODO: tests, check if resource exists

P.S. I think that db is not ACID compliant now

### CODE REVIEW

**Comment by abhinav-TB** [comment]
Hey, @illiafox thanks for your contributions, they would be a great addition to the codebase

There are a few things I would suggest you to  update
- add the database directory that will be created from the running example. go file to .gitingnore
- Change the contribute section in the readme to Top Contributors then add your name without mentioning changes (this is the most common practice followed )

**Comment by illiafox** [comment]
#[3d6bd90](https://github.com/abhinav-TB/dantdb/pull/2/commits/3d6bd90d049e2828d67875a8435bc8fba04756b2)

**Comment by illiafox** [comment]
By the way,  what's the purpose for creating .tmp files? With Mutex db can write directly

**Comment by abhinav-TB** [comment]
> By the way, what's the purpose for creating .tmp files? With Mutex, db can write directly

Thanks for pointing it out, I didn't remove it after adding mutexes, could you  change that as well in this pr

**Comment by illiafox** [comment]
already done

**Comment by abhinav-TB** [comment]
All looks good, merging it !!!

**Pull request merged**
